'use strict';

module.exports = {
  MONGO_DATA_DIR: process.env.MONGO_DATA_DIR, 
  MONGO_LOG_DIR: process.env.MONGO_LOG_DIR,
  MONGO_INITDB_ROOT_USERNAME: process.env.MONGO_INITDB_ROOT_USERNAME,  
  MONGO_INITDB_ROOT_PASSWORD: process.env.MONGO_INITDB_ROOT_PASSWORD,
  MONGO_INITDB_DATABASE: process.env.MONGO_INITDB_DATABASE,
  EXPRESS_PORT: process.env.EXPRESS_PORT,
}