module.exports = {
  SALT_ROUNDS: 10,
  UNIX_HALF_HOUR: 1800000,
  MINIMUM_PASSWORD_LENGTH: 6,
  CHAT_MESSAGE_LOAD_LIMIT: 10,
  DRIVE_FILE_TYPES: {
    IMAGE: 'Image',
    FOLDER: 'Folder',
  },
  SUBSCRIPTION_TRIGGER: {
    NEW_CHAT_MESSAGE: 'NEW_CHAT_MESSAGE',
    USER_UPDATED: 'USER_UPDATED',
    NEW_COMMENT_ADDED: 'NEW_COMMENT_ADDED-',
    NEW_TAG_ADDED: 'NEW_TAG_ADDED-',
  },
};
